apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: posts
  template:
    metadata:
      labels:
        component: posts
    spec:
      serviceAccountName: config-reader
      containers:
        - name: posts
          image: mikebychkov/sb-posts:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: "PROFILE"
              value: "kube"
            - name: "DB_SERVER"
              value: "tcp://db-cluster-ip-service:5432"
            - name: "KAFKA_SERVER"
              value: "http://kafka-cluster-ip-service:9092"
            - name: "ZK_SERVER"
              value: "zookeeper-cluster-ip-service"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 5001
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /actuator/health
          #     port: 5001
          #     scheme: HTTP
          #   initialDelaySeconds: 180
          #   successThreshold: 1
