apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  application.yaml: |-
    some:
      config:
        value: FUCKWARMAKELOVE
    logging:
      level:
        org.springframework.cloud: DEBUG
        org.mike: DEBUG
