apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  application.yaml: |-
    some:
      config:
        value: FUCKWARMAKELOVE
    logging:
      level:
        org.springframework.cloud: WARN
        org.mike: DEBUG
    security:
      oauth2:
        resource:
          user-info-uri: http://auth-cluster-ip-service:5005/user/
