apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: "p9092"
    - port: 9094
      targetPort: 9094
      name: "p9094"
