apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      containers:
        - name: kafka
          #image: wurstmeister/kafka
          image: mikebychkov/kafka
          ports:
            - containerPort: 9092
            - containerPort: 9094
          env:
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "zookeeper-cluster-ip-service"
            - name: "KAFKA_LISTENERS"
              value: "INSIDE://:9092,OUTSIDE://:9094"
            - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
              value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
            - name: "KAFKA_INTER_BROKER_LISTENER_NAME"
              value: "INSIDE"
