apiVersion: v1
kind: Pod
metadata:
  name: posts-pod
  labels:
    component: web
spec:
  containers:
    - name: posts
      image: mikebychkov/sb-posts
      ports:
        - containerPort: 5001
      env:
        - name: "PROFILE"
          value: "doc"
    - name: db
      image: postgres:12.5
      ports:
        - containerPort: 5432
      env:
        - name: "POSTGRES_USER"
          value: "postgres"
        - name: "POSTGRES_PASSWORD"
          value: "Zxcv1234"
        - name: "POSTGRES_DB"
          value: "sb_posts"
