apiVersion: apps/v1
kind: Deployment
metadata:
  name: finder-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: finder
  template:
    metadata:
      labels:
        component: finder
    spec:
      serviceAccountName: config-reader
      containers:
        - name: finder
          image: mikebychkov/sb-finder:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: "PROFILE"
              value: "kube"
            - name: "REDIS_SERVER"
              value: "tcp://redis-cluster-ip-service:6379"
            - name: "KAFKA_SERVER"
              value: "tcp://kafka-cluster-ip-service"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 5002
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /actuator/health
          #     port: 5002
          #     scheme: HTTP
          #   initialDelaySeconds: 180
          #   successThreshold: 1
